version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-social}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  jupyter:
    image: python:3.11
    container_name: jupyter
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - mongo
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=social
      - PG_USER=postgres
      - PG_PASS=postgres
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=social
    command: >
      sh -c "pip install jupyter jupyterlab pandas numpy matplotlib seaborn psycopg2-binary pymongo python-dotenv &&
             jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"

volumes:
  pg_data:
  mongo_data:
